name: flutter_app
description: Careerise Flutter app with login/register/dashboard
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  http: ^0.13.6
  shared_preferences: ^2.2.2
  file_picker: ^10.3.2
  image_picker: ^1.1.0
  percent_indicator: ^4.2.2
  url_launcher: ^6.3.1
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/animations/score_dial.json